### PR TITLE
Update Godots to 1.3.stable

### LINKED ISSUE #3: Update Godots
The latest version of [Godots is v1.3 stable](https://github.com/MakovWait/godots/releases/tag/v1.3.stable), there have been multiple new features introduced and a redesign.

It would be nice to have this Flatpak updated to the newest release

### PR DESCRIPTION
**Pull request by AsciiWolf**
Replaces #4.
Closes #3.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Seems to be a linter issue. I have removed the 1.2.2 release from AppStream metadata to workaround it.

**Comment by CharlieQLe** [comment]
Sorry I haven't been around, this looks good other than the script errors. Before merging, I'd like to look into the errors to see if they can be fixed upstream just in case it actually does conflict with something.

**Comment by AsciiWolf** [comment]
@CharlieQLe Were you able to identify the errors?

**Comment by AsciiWolf** [comment]
@CharlieQLe Any update?

**Comment by AsciiWolf** [comment]
@CharlieQLe Were you able to identify the errors?

**Comment by CharlieQLe** [comment]
> @CharlieQLe Were you able to identify the errors?

Sorry for the lack of updates. I wasn't able to identify the error, but I'll update the flatpak since it seems to work fine regardless.

**Pull request merged**
