### PR TITLE
Update Godots to 1.3.stable

### PR DESCRIPTION
**Pull request by coffandro**
This PR updates Godots to the latest stable release

### CODE REVIEW

**Comment by coffandro** [comment]
@CharlieQLe there a chance you'd be willing to look at this?

**Comment by CharlieQLe** [comment]
> @CharlieQLe there a chance you'd be willing to look at this?

Looks like an error with a metadata file upstream regarding changelog.

**Comment by coffandro** [comment]
And how would you fix that?

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
@coffandro This needs to be added as a downstream patch for the Flatpak: https://github.com/MakovWait/godots/pull/97/files

**Comment by AsciiWolf** [comment]
Here is more info about patches in Flatpaks:

https://docs.flatpak.org/en/latest/module-sources.html#patch-sources

Let me know if you need any help.

**Comment by coffandro** [comment]
I don't have the time to try to get this shit working, please someone else create a PR if it is

**Pull request closed without merging**
